os:
  - linux

language: php

php:
  - '7.3'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - pear install pear/PHP_CodeSniffer

script:
  - php artisan key:generate
  - vendor/bin/phpunit --coverage-text